import {mountViewer} from '/item-viewer.js';
const $=id=>document.getElementById(id);let state,filter='All',changeFilter='All production',selected,token,disposeViewer,viewerEpoch=0,roomKey='',historyKey='',referenceVersion,reviewVersion,draftLoaded=false;let draftWrites=Promise.resolve();const categories=['All','People','Workspaces','Operations','Furniture','Identity','Atmosphere','Architecture'];
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function notice(message){$('notice').textContent=message;$('notice').hidden=false;setTimeout(()=>$('notice').hidden=true,5000);}
function production(a){if(a.feedback||a.choice==='generate')return 'Changes requested';if(a.choice==='reuse')return 'Reuse selected';if(a.shared)return 'Shared defaults';if(a.pilot?.state==='ready')return 'Existing candidates';if(a.method==='Code-built')return 'Exact / code-built';return 'New designs';}
const productionFilters=['All production','Recommended to recreate','New designs','Changes requested','Shared defaults','Existing candidates','Reuse selected','Exact / code-built'];
function paint(){
 if(!draftLoaded){draftLoaded=true;const d=state.draft??{};referenceVersion=d.baseVersion;$('room-feedback').value=d.feedback??'';if(d.model)$('room-model').value=d.model;if(d.useExisting!==undefined)$('use-existing').checked=d.useExisting;}
 paintRoom();paintHistory();
 $('connection').textContent='Local records connected';$('total').textContent=state.assets.length;$('ready').textContent=state.ready;
 $('storage-status').textContent=`Saved locally · ${state.storage?.engine??'JSON'} · ${state.storage?.fileCount??0} indexed asset files`;
 $('updated').textContent='Updated '+new Date(state.updatedAt).toLocaleTimeString();
 const built=state.assets.filter(a=>a.generatedModel?.status==='ready'||a.pilot?.state==='ready'||a.method==='Code-built'||a.id==='art'&&a.concept?.status==='ready').length;
 $('rail-count').textContent=`${built} / ${state.assets.length}`;$('rail-progress').value=built;$('rail-progress').max=state.assets.length;$('rail-progress-note').textContent=`${state.ready} generated models · final review pending`;
 const groups=[['Direction','A shared vision',0],['Collection','Every object considered',3],['Production','From image to form',5],['Your office','Bring it all together',7]];
 $('stages').replaceChildren(...groups.map(([title,subtitle,start],i)=>{const section=el('section',undefined,'journey-group');const h=el('div',undefined,'journey-heading');h.append(el('span',String(i+1).padStart(2,'0'),'journey-number'));const label=el('div');label.append(el('strong',title),el('small',subtitle));h.append(label);section.append(h);const end=groups[i+1]?.[2]??state.stages.length;state.stages.slice(start,end).forEach(step=>{const link=el('a',undefined,'journey-step');link.href=start<3?'#concept':'#collection';link.dataset.state=step.state;link.title=step.detail;const copy=el('span',step.name);copy.append(el('small',step.detail));const status=step.badge??(step.state==='complete'?'Ready':step.state==='next'?'Review':'Pending');link.append(copy,el('em',status));section.append(link)});return section;}));

 if(state.review)$('brief-text').textContent=state.review.direction.slice(0,420)+(state.review.direction.length>420?'…':'');
 $('review').replaceChildren(el('p',state.review?`${state.review.reviewer} · ${state.review.commit.slice(0,10)} · ${state.review.summary}\n\n${state.review.direction}`:'Local repository evidence is available. No completed Claude review has been recorded yet.'),...((state.review?.evidence??state.brief?.evidence??[]).map(e=>el('p',`${e.path} · ${e.sha256.slice(0,12)}`))));
 $('filters').replaceChildren(...categories.map(c=>{const b=el('button',c);b.setAttribute('aria-pressed',String(c===filter));b.onclick=()=>{filter=c;paint();};return b;}));
 $('change-summary').textContent='Production plan · '+productionFilters.filter(c=>!['All production','Recommended to recreate'].includes(c)).map(c=>`${state.assets.filter(a=>production(a)===c).length} ${c.toLowerCase()}`).join(' · ');
 $('change-filters').replaceChildren(...productionFilters.map(c=>{const b=el('button',c);b.setAttribute('aria-pressed',String(c===changeFilter));b.onclick=()=>{changeFilter=c;paint();};return b;}));
 $('cards').replaceChildren(...state.assets.filter(a=>(filter==='All'||a.category===filter)&&(changeFilter==='All production'||(changeFilter==='Recommended to recreate'?!!a.recommendation:production(a)===changeFilter))).map(a=>{const card=el('article',undefined,`card ${a.pilot?.state==='ready'?'ready':''}`);card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',`Review ${a.name}`);card.onclick=()=>inspect(a.id);card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect(a.id);}};const inner=el('div',undefined,'card-inner');const media=el('div',undefined,'card-media');if(a.preview||a.method==='Code-built'){const img=el('img');img.src=a.preview??(a.id==='brand'?'/project-logo.svg':`/native-${a.id}.png`);img.alt=`Generated ${a.name} pilot preview`;img.onerror=()=>{img.hidden=true;};media.append(img);}else{media.append(el('span',String(state.assets.indexOf(a)+1).padStart(2,'0'),'number'),el('span','Concept image not generated','placeholder-caption'));}if(a.generatedModel)media.append(el('span','3D / '+a.generatedModel.status.toUpperCase(),'model-status'));media.append(el('span',a.concept?`IMAGE / ${a.approved?'APPROVED':a.concept.status.toUpperCase()}`:a.pilot?.state==='ready'?'PILOT / VISUAL REVIEW':a.pilot?.state==='generating'?'GENERATING':a.method==='Code-built'?'NATIVE / LIVE':a.shared?'DEFAULT KIT / PLANNED':'DESIGN PENDING','badge'));const body=el('div',undefined,'card-body');body.append(el('span',a.category.toUpperCase(),'overline'),el('h3',a.name),el('p',a.description));const foot=el('div',undefined,'card-foot');foot.append(el('span',a.choice==='reuse'?'Reuse selected':a.choice==='generate'?'New design selected':a.shared?'Shared default':a.method),el('span',a.feedback?'Feedback saved ↗':'Inspect item ↗'));const productionTag=el('span',production(a),'production-tag');productionTag.dataset.kind=production(a);body.prepend(productionTag);if(a.recommendation){body.append(el('strong',a.id==='brand'?'EXACT ARTWORK REQUIRED':'RECOMMENDED TO RECREATE','recommendation'),el('p',a.recommendation));}body.append(foot);inner.append(media,body);card.append(inner);return card;}));
 const batch=state.batch??{missing:[],jobs:[],active:0};$('generate-items').disabled=!state.roomApproved||!batch.missing.length||!!batch.active;$('generate-items').textContent=`Generate all missing items (${batch.missing.length})`;$('batch-summary').textContent=!state.roomApproved?'Approve a room design to unlock item generation.':`${batch.missing.length} missing custom images · model: ${$('room-model').selectedOptions[0]?.textContent}`;$('batch-items').textContent=batch.missing.map(a=>a.name).join(' · ');$('batch-status').replaceChildren(...batch.jobs.map(j=>el('p',`${j.name} · ${j.status}${j.visualReview?.outcome==='rejected'?' · Visual review: needs correction':''}${j.error?' · '+j.error:''}`)));
 $('events').replaceChildren(...(state.events.length?state.events.slice(-6).reverse().map(e=>el('p',`${new Date(e.at).toLocaleTimeString()} · ${e.item} · ${e.action==='feedback'?'Feedback saved':e.action==='reuse'?'Existing model selected':'New design requested'}`)):[el('p','No design decisions recorded yet. Open an item to add feedback or choose reuse.')]));
}
function inspect(id){disposeViewer?.();disposeViewer=null;const epoch=++viewerEpoch;selected=state.assets.find(a=>a.id===id);$('item-name').textContent=selected.name;$('item-category').textContent=selected.category.toUpperCase();$('item-description').textContent=selected.description+(selected.generatedModel?' · 3D: '+selected.generatedModel.status:'')+(selected.generatedModel?.integrationReview?' · Integration review: '+selected.generatedModel.integrationReview.notes:'');$('feedback').value=selected.feedback;$('item-media').replaceChildren();if(selected.generatedModel?.renderFile){const img=el('img');img.src='/'+selected.generatedModel.renderFile;img.alt='Rendered 3D model of '+selected.name;$('item-media').append(img);}else if(selected.preview||selected.method==='Code-built'){const img=el('img');img.src=selected.preview??(selected.id==='brand'?'/project-logo.svg':`/native-${selected.id}.png`);img.alt=selected.method==='Code-built'?'Native office component':'Design reference';$('item-media').append(img);}else $('item-media').append(el('p','A sample image will appear here after the room direction is approved.'));
 const changes=state.events.filter(e=>e.item===selected.name);$('item-history').replaceChildren(el('p',selected.pilot?`Pilot · ${selected.pilot.state} · ${selected.version.slice(0,12)}`:'No generated asset version yet.'),...changes.map(e=>el('p',`${new Date(e.at).toLocaleString()} · ${e.action}${e.text?' · '+e.text:''}`)));
 for(const [index,v] of (selected.conceptVersions??[]).entries()){const row=el('div');row.append(el('p',`Image v${index+1} · ${v.status}${v.visualReview?' · '+v.visualReview.outcome:''}`));if(v.file){const link=el('a','Open saved image ↗');link.href='/'+v.file;link.target='_blank';link.rel='noopener';row.append(link);}if(v.visualReview?.notes)row.append(el('p',v.visualReview.notes));$('item-history').append(row);}
 $('item-actions').replaceChildren();$('viewer-hint').textContent='';
 if(selected.pilot?.state==='ready'||selected.generatedModel?.status==='ready'){
  const view=el('button','View 3D here');view.onclick=async()=>{view.disabled=true;$('item-media').classList.add('viewer');$('viewer-hint').textContent='Loading model…';try{const cleanup=await mountViewer($('item-media'),selected.generatedModel?.file?'/'+selected.generatedModel.file:selected.pilot.url);if(epoch!==viewerEpoch){cleanup();return;}disposeViewer=cleanup;$('viewer-hint').textContent='Drag to rotate · scroll to zoom · pilot materials need visual review';}catch{$('viewer-hint').textContent='Could not load the model';view.disabled=false;}};
  const reuse=el('button',selected.choice==='reuse'?'Reuse selected ✓':'Choose existing model');reuse.onclick=()=>send('reuse');$('item-actions').append(view);if(selected.pilot?.state==='ready')$('item-actions').append(reuse);
 }
 if(selected.concept?.status==='ready'){const approve=el('button',selected.approved?'Image approved ✓':'Approve item image');approve.disabled=selected.approved;approve.onclick=()=>send('approve-image');$('item-actions').append(approve);}
 const fresh=el('button','Choose a new design');fresh.onclick=()=>send('new');$('item-actions').append(fresh);if(selected.shared)$('item-description').textContent+=' Shared default component: intended to be reused across repositories. Default-kit extraction is still pending.';$('inspector').showModal();}
$('inspector').addEventListener('close',()=>{viewerEpoch++;disposeViewer?.();disposeViewer=null;$('item-media').classList.remove('viewer');});
function paintHistory(){const versions=state.room?.versions??[];const key=JSON.stringify([versions,referenceVersion,state.room.approvedVersion]);if(key===historyKey)return;historyKey=key;
 $('reference-selection').textContent=referenceVersion?`Room v${referenceVersion} selected for the next generation. Selection does not approve it.`:'Latest room used as the next reference. Choose an earlier version below.';
 $('room-history').replaceChildren(...versions.map(v=>{const card=el('article',undefined,'history-card');if(v.file){const link=el('a');link.href='/'+v.file;link.target='_blank';link.rel='noopener';const img=el('img');img.src='/'+v.file;img.alt=`Room concept version ${v.id}`;link.append(img);card.append(link);}card.append(el('h3',`Room v${v.id} · ${v.approvedHash?'Approved':v.status}`),el('small',v.model??'fal-ai/flux-2-pro/edit'),el('p',v.feedback||'Original direction'),el('small',new Date(v.createdAt).toLocaleString()));const detail=el('details'),summary=el('summary','Prompt & references');detail.append(summary,el('p',v.prompt),el('p',`Base: ${v.baseVersion?'room v'+v.baseVersion:v.previousImage??'initial references'} · Existing assets: ${(v.assetReferences??[]).map(r=>r.id).join(', ')||'none'}`));card.append(detail);const select=el('button',referenceVersion===v.id?'Reference selected ✓':'Use as room reference');select.disabled=v.status!=='ready'||!v.file;select.setAttribute('aria-pressed',String(referenceVersion===v.id));select.onclick=()=>{referenceVersion=v.id;persistDraft();paintHistory();notice(`Room v${v.id} selected. No generation started.`);};const approve=el('button',state.room.approvedVersion===v.id?'Approved design ✓':'Review & approve');approve.disabled=v.status!=='ready'||!v.file;approve.onclick=()=>{reviewVersion=v.id;roomKey='';paintRoom();$('concept').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});notice(`Reviewing room v${v.id}. Confirm the checklist, then approve.`);};card.append(select,approve);return card;}));}
function reviewedRoom(){return state.room?.versions.find(v=>v.id===reviewVersion)??state.room?.versions.at(-1);}
function paintRoom(){const room=state.room;const v=reviewedRoom();$('model-provenance').textContent='Model · '+(v?.model??'fal-ai/flux-2-pro/edit');const key=JSON.stringify([room?.revision,v?.id,v?.status,v?.sha256,v?.approvedHash]);
 if(key!==roomKey){roomKey=key;$('room-status').textContent=v?`Revision ${v.id} · ${v.approvedHash===v.sha256&&v.sha256?'approved':v.status}${v.error?' · '+v.error:''}`:'Ready for the first concept image';
  $('room-frame-top').lastElementChild.textContent=v?.status==='ready'?`Concept v${v.id} · ${v.approvedHash?'approved':'review required'}`:v?.status??'Awaiting concept image';
  if(v?.file){const link=el('a');link.href='/'+v.file;link.target='_blank';link.rel='noopener';const img=el('img');img.src='/'+v.file;img.alt='Generated Xarts room concept revision '+v.id;link.append(img);$('room-image-container').replaceChildren(link);$('room-image-container').classList.add('generated');}
  $('room-checklist').replaceChildren(...state.requirements.map(([id,label])=>{const row=el('label');const input=el('input');input.type='checkbox';input.value=id;input.checked=!!v?.checked?.includes(id)||!!(state.draft?.imageHash===v?.sha256&&state.draft?.checked?.includes(id));input.disabled=v?.status!=='ready'||(!!v?.approvedHash&&state.room.approvedVersion===v.id);input.onchange=()=>{approvalState();persistDraft();};row.append(input,document.createTextNode(label));return row;}));
 }
 const running=v&&['planned','submitting','queued','generating','paused'].includes(v.status);$('generate-room').disabled=!!running;$('generate-room').textContent=v?'Regenerate with feedback':'Generate room image';approvalState();
 const next=$('next');next.querySelector('b').textContent=state.roomApproved?'Room direction approved.':v?.status==='ready'?'Your room concept is ready to review.':'Next: define the whole room.';next.querySelector('p').textContent=state.roomApproved?'This revision becomes the reference for individual item designs.':v?.status==='ready'?'Inspect the image and confirm each required component before approving.':'The image uses style, layout and logo references. Generation progress is shown below.';
}
function approvalState(){const v=reviewedRoom();const boxes=[...document.querySelectorAll('#room-checklist input')];const remaining=boxes.filter(x=>!x.checked).length;const approved=!!v?.approvedHash&&state.room.approvedVersion===v.id;$('confirm-all').disabled=!v||v.status!=='ready'||approved;$('confirm-all').textContent=remaining?'All items look good':'Clear checklist';$('approve-room').disabled=!v||v.status!=='ready'||approved||remaining>0;$('approve-room').textContent=approved?'Revision approved':'Approve this revision';$('approval-help').textContent=approved?'This exact image revision is approved.':v?.status!=='ready'?'Approval becomes available when the image is ready.':remaining?`${boxes.length-remaining} of ${boxes.length} components confirmed. Review and tick the ${remaining} remaining items to enable approval. If a component is missing or incorrect, leave it unchecked and request a revision below.`:'All required components confirmed. You can now approve this image.';}

async function roomAction(action){const v=reviewedRoom();const button=action==='generate'?$('generate-room'):$('approve-room');button.disabled=true;try{const r=await fetch('/room-command',{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify({action,version:action==='approve'?v?.id:undefined,baseVersion:referenceVersion,model:$('room-model').value,useExisting:$('use-existing').checked,revision:state.room.revision,hash:v?.sha256,checked:[...document.querySelectorAll('#room-checklist input:checked')].map(x=>x.value),feedback:$('room-feedback').value})});const data=await r.json();if(!r.ok)throw Error(data.error??'Request failed');state.room=data;state.roomApproved=!!data.approvedVersion;paintRoom();notice(action==='approve'?'Room revision approved.':'One room image requested.');}catch(e){notice(e.message);paintRoom();}}
function persistDraft(){if(!state||!token)return;const draft={feedback:$('room-feedback').value,model:$('room-model').value,useExisting:$('use-existing').checked,baseVersion:referenceVersion,checked:[...document.querySelectorAll('#room-checklist input:checked')].map(x=>x.value),imageHash:reviewedRoom()?.sha256??null};state.draft=draft;draftWrites=draftWrites.then(async()=>{const r=await fetch('/draft',{method:'POST',keepalive:true,headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify(draft)});if(!r.ok)throw Error('Draft not saved');}).catch(()=>notice('Could not save your draft. Keep this tab open and retry.'));}
$('room-feedback').oninput=persistDraft;$('room-model').onchange=persistDraft;$('use-existing').onchange=persistDraft;
$('generate-items').onclick=async()=>{const b=$('generate-items');b.disabled=true;try{const r=await fetch('/generate-items',{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify({revision:state.revision,roomRevision:state.room.revision,model:$('room-model').value})});const data=await r.json();if(!r.ok)throw Error(data.error??'Batch could not start');notice(`${data.queued} item images queued. Progress is saved locally.`);const fresh=await fetch('/progress');state=await fresh.json();paint();}catch(e){notice(e.message);b.disabled=false;}};
$('confirm-all').onclick=()=>{const boxes=[...document.querySelectorAll('#room-checklist input')];const checked=boxes.some(x=>!x.checked);boxes.forEach(x=>x.checked=checked);approvalState();persistDraft();};
$('generate-room').onclick=()=>roomAction('generate');$('approve-room').onclick=()=>roomAction('approve');

async function send(action){try{const r=await fetch('/decisions',{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify({action,id:selected.id,version:selected.version,revision:state.revision,text:$('feedback').value})});const result=await r.json();if(!r.ok)throw Error(result.error??'Unable to save');state=result;paint();$('inspector').close();notice(action==='approve-image'?'Item image approved.':action==='feedback'?'Feedback saved. No generation started.':'Selection saved. No generation started.');}catch(e){notice(e.message);}}$('save-feedback').onclick=()=>send('feedback');
async function poll(){try{const session=await fetch('/session',{cache:'no-store'});if(!session.ok)throw Error('Session unavailable');token=(await session.json()).token;const r=await fetch('/progress');if(!r.ok)throw Error();const next=await r.json();state=next;paint();}catch{$('connection').textContent='Status unavailable · retrying';}setTimeout(poll,5000);}poll();
