import * as THREE from '/vendor/three.module.js';
import {GLTFLoader} from '/vendor/GLTFLoader.js';
import {OrbitControls} from '/vendor/OrbitControls.js';
import {HDRLoader} from '/vendor/HDRLoader.js';
export async function mountViewer(host,url){
 const scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.replaceChildren(renderer.domElement);const camera=new THREE.PerspectiveCamera(35,1,.01,100);camera.position.set(3,1.8,4);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,.9,0);controls.minDistance=2;controls.maxDistance=8;scene.add(new THREE.HemisphereLight(0xf4f8ff,0x718178,1.5));const light=new THREE.DirectionalLight(0xfff4e4,2);light.position.set(3,5,4);light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.normalBias=.03;scene.add(light);const floor=new THREE.Mesh(new THREE.CircleGeometry(3.8,80),new THREE.MeshStandardMaterial({color:0xe8ece8,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.015;floor.receiveShadow=true;scene.add(floor);let mixer,disposed=false,raf,environment;
 new HDRLoader().load('/studio.hdr',t=>{if(disposed){t.dispose();return;}environment=t;t.mapping=THREE.EquirectangularReflectionMapping;scene.environment=t;scene.environmentIntensity=.6;});
 const resize=()=>{const r=host.getBoundingClientRect();if(r.width&&r.height){renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}};const observer=new ResizeObserver(resize);observer.observe(host);
 const cleanup=()=>{disposed=true;cancelAnimationFrame(raf);observer.disconnect();controls.dispose();environment?.dispose();scene.traverse(n=>{n.geometry?.dispose();for(const m of Array.isArray(n.material)?n.material:n.material?[n.material]:[]){for(const x of Object.values(m))if(x?.isTexture)x.dispose();m.dispose();}});renderer.dispose();renderer.domElement.remove();};
 try{const gltf=await new GLTFLoader().loadAsync(url);const model=gltf.scene;const size=new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3());model.scale.multiplyScalar(2/Math.max(size.x,size.y,size.z));const box=new THREE.Box3().setFromObject(model),center=box.getCenter(new THREE.Vector3());model.position.add(new THREE.Vector3(-center.x,-box.min.y,-center.z));model.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=false;}if(n.material)for(const m of Array.isArray(n.material)?n.material:[n.material]){m.emissiveIntensity=0;if(m.map){m.map.minFilter=THREE.LinearFilter;m.map.generateMipmaps=false;m.map.anisotropy=renderer.capabilities.getMaxAnisotropy();m.map.needsUpdate=true;}if(m.specularIntensity!==undefined)m.specularIntensity=.3;if(!m.metalnessMap){m.metalness=0;m.roughness=Math.max(.8,m.roughness);}};});scene.add(model);if(gltf.animations.length){mixer=new THREE.AnimationMixer(model);mixer.clipAction(gltf.animations[0]).play();}resize();let last=0;const motion=!matchMedia('(prefers-reduced-motion:reduce)').matches;function frame(t){if(disposed)return;raf=requestAnimationFrame(frame);if(document.hidden||t-last<32)return;const dt=Math.min((t-last)/1000,.1);last=t;// Stable inspection pose: orbit the model without a looping root turn.
controls.update();renderer.render(scene,camera);}raf=requestAnimationFrame(frame);return cleanup;}catch(e){cleanup();throw e;}
}
