import {officeBrand} from './brand-profile.mjs';
import {storage} from './storage.mjs';
import {projectEnvironment} from '../server/environment.mjs';
import{readFile,writeFile,rename,mkdir}from'node:fs/promises';import{join}from'node:path';import{createHash}from'node:crypto';import{dir,root,load}from'./pipeline.mjs';
export const roomModel='fal-ai/flux-2-pro/edit';
export const roomModels=[roomModel,'fal-ai/nano-banana-pro/edit','openai/gpt-image-2.5/flare/edit'];
export function modelInput(model,prompt,images){if(!roomModels.includes(model))throw Error('Unsupported room model');const common={prompt,image_urls:images,output_format:'png'};return model==='fal-ai/nano-banana-pro/edit'?{...common,aspect_ratio:'3:2',resolution:'2K',num_images:1}:model.startsWith('openai/')?{...common,image_size:{width:1536,height:1024},quality:'high',num_images:1}:{...common,image_size:{width:1536,height:1024}};}
export function queueBase(model){if(!roomModels.includes(model))throw Error('Unsupported room model');return 'https://queue.fal.run/'+model.split('/').slice(0,2).join('/');}
export const requirements=[['engineering','Engineering desk, monitor, keyboard, lamp and mug'],['backlog','Four-column work queue board'],['planning','Separate CEO planning desk'],['ideas','Product / marketing ideas wall'],['quality','Quality dashboard'],['conveyor','Conveyor with exactly four gates'],['safe','Safe with wheel, door and budget screen'],['ticker','Wall activity ticker'],['brand','Turquoise Xarts letters without a black rectangle'],['people','Four adults: CEO, engineer, QA and product/marketing'],['plants','Plants and editorial art'],['slide','Curved orange slide inside the room footprint']];
export async function roomState(){return storage().get('room',{revision:0,versions:[]});}
async function save(s){storage().put('room',s);await mkdir(dir,{recursive:true});await writeFile(join(dir,'room.tmp'),JSON.stringify(s,null,2));await rename(join(dir,'room.tmp'),join(dir,'room.json'));}
export function validateApproval(v,command){if(!v||v.status!=='ready'||command.hash!==v.sha256)throw Error('Approve the current completed image revision');if(!Array.isArray(command.checked)||requirements.some(([id])=>!command.checked.includes(id)))throw Error('Confirm every mandatory component before approval');}
export async function api(url,body){const key=projectEnvironment(root).FAL_KEY;if(!key)throw Error('fal key not configured');const r=await fetch(url,{method:body?'POST':'GET',headers:{Authorization:`Key ${key}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(90000)});if(!r.ok)throw Error(`fal HTTP ${r.status}`);return r.json();}
let busy=false;
async function worker(s,v){try{
 if(!v.requestId){
  if(v.status==='submitting')throw Error('Submission outcome unknown; no paid retry made');
  const images=[];for(const file of ['style.png','layout.png','logo.png'])images.push('data:image/png;base64,'+(await readFile(join(dir,'references',file))).toString('base64'));
  if(v.previousImage)images.push('data:image/png;base64,'+(await readFile(join(dir,v.previousImage))).toString('base64'));
  for(const ref of v.assetReferences??[])images.push('data:image/png;base64,'+(await readFile(join(dir,ref.file))).toString('base64'));
  v.status='submitting';await save(s);const result=await api('https://queue.fal.run/'+(v.model??roomModel),modelInput(v.model??roomModel,v.prompt,images));v.requestId=result.request_id;v.status='queued';await save(s);
 }
 for(let i=0;i<120;i++){
  const base=`${queueBase(v.model??roomModel)}/requests/${encodeURIComponent(v.requestId)}`;const status=await api(base+'/status');v.status=status.status==='IN_QUEUE'?'queued':'generating';await save(s);
  if(status.status==='COMPLETED'){
   const result=await api(base);const url=new URL(result.images?.[0]?.url);if(url.protocol!=='https:'||!(url.hostname==='fal.media'||url.hostname.endsWith('.fal.media')))throw Error('Unexpected image host');const r=await fetch(url,{signal:AbortSignal.timeout(60000)});if(!r.ok)throw Error('Image download failed');let size=0;const chunks=[];for await(const b of r.body){size+=b.length;if(size>25e6)throw Error('Image exceeds limit');chunks.push(b);}const data=Buffer.concat(chunks);if(data.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('Expected PNG image');
   v.file=`room-v${v.id}.png`;await writeFile(join(dir,v.file),data);v.sha256=createHash('sha256').update(data).digest('hex');v.status='ready';v.completedAt=new Date().toISOString();await save(s);return;
  }await new Promise(r=>setTimeout(r,5000));
 }v.status='paused';v.error='Polling timed out. Resume the existing request; do not resubmit.';await save(s);
 }catch(e){v.status='failed';v.error=e.message;await save(s);}finally{busy=false;}}
export async function roomCommand(c){if(busy)throw Error('Room generation is already running');busy=true;try{const s=await roomState();if(c.revision!==s.revision)throw Error('Room revision changed; refresh before continuing');const v=s.versions.at(-1);
 if(c.action==='approve'){const target=c.version===undefined?v:s.versions.find(x=>x.id===c.version);validateApproval(target,c);target.approvedHash=target.sha256;target.approvedAt=new Date().toISOString();target.checked=c.checked;s.approvedVersion=target.id;s.revision++;await save(s);busy=false;return s;}
 if(c.action!=='generate')throw Error('Unknown room action');if(v&&['queued','submitting','generating','paused'].includes(v.status))throw Error('Existing request must finish or be resumed first');
 const feedback=typeof c.feedback==='string'?c.feedback.trim():'';if(feedback.length>3000)throw Error('Feedback is too long');if(v&&!feedback)throw Error('Describe what should change in the next revision');
 const model=c.model??'fal-ai/nano-banana-pro/edit';if(!roomModels.includes(model))throw Error('Unsupported room model');
 const baseVersion=c.baseVersion===undefined?v:s.versions.find(x=>x.id===c.baseVersion&&x.status==='ready'&&x.file);if(c.baseVersion!==undefined&&!baseVersion)throw Error('Selected room reference is unavailable');
 const pilot=await load();const assetReferences=[];if(c.useExisting)for(const id of ['chair','engineer']){const asset=pilot?.assets.find(a=>a.id===id&&a.state==='ready');if(asset){const file=id+'-provider-preview.png';const bytes=await readFile(join(dir,file));assetReferences.push({id,file,sha256:createHash('sha256').update(bytes).digest('hex'),modelHash:asset.validation?.sha256});}}
 if(Array.isArray(c.referenceItems)){const jobs=storage().get('item-images',{jobs:[]}).jobs;for(const id of [...new Set(c.referenceItems)].slice(0,6)){if(typeof id!=='string')throw Error('Invalid reference item');const image=jobs.filter(j=>j.itemId===id&&j.status==='ready'&&j.visualReview?.outcome==='accepted-for-preview').at(-1);if(!image)throw Error('Reviewed item reference required');const bytes=await readFile(join(dir,image.file));if(createHash('sha256').update(bytes).digest('hex')!==image.sha256)throw Error('Reference hash mismatch');assetReferences.push({id,file:image.file,sha256:image.sha256});}}
 const referencePrompt=assetReferences.map((r,i)=>`Image ${4+(baseVersion?.file?1:0)+i} is our existing ${r.id} candidate: preserve recognizable design and proportions, do not invent a replacement; characters may vary clothing and pose.`).join(' ');
 const review=storage().get('claude-review',null);if(!review)throw Error('Repository review is required');
 const prompt=`Create one premium photorealistic architectural product visualization of the entire Xarts Office, isometric landscape view. Image 1 is the style reference: adult realistic staff, materials and polish. Image 2 is the functional inventory and placement reference ONLY, do not copy primitive geometry or app overlays. Image 3 is exact brand artwork, not a style suggestion: preserve its letter shapes and spelling, no added letters, no substitute typeface, no rectangle. Never invent an alternative logo. Production uses the original SVG unchanged. ${baseVersion?.file?'Image 4 is the previous room revision and PRIMARY spatial reference. Preserve camera, room footprint, positions, materials and all objects unless feedback explicitly requests changes. Edit only requested components; do not redesign the whole room.':''} Use ${officeBrand.materials}. Dramatic sculptural design, daylight with balanced shadows, no blur. All components distinct, visible and unobscured. Mandatory: ${requirements.map(([,x])=>x).join('; ')}. Four conveyor placards read Scope, Chart correctness, Regressions, Release. Place exactly four adults at their workstations: CEO at rear planning desk, engineer at front-left, QA next to conveyor, product lead near ideas wall. Keep enough circulation and no overlapping equipment. Use accurate adult anatomy and contemporary outfits. No UI, browser chrome, watermark or fake metrics. ${review.roomPrompt} Reuse-first constraint: retain ordinary desks, architecture, plants, safe, ticker and QA machinery from the layout reference. Customization is limited to the exact-logo board, four staff variations, and two or three statement furniture pieces (lounge, slide and optional planning desk). Do not add extra custom objects or redesign shared equipment. ${referencePrompt} User feedback: ${feedback||'First image. Prioritize complete inventory and a bold coherent silhouette.'}`;
 const next={model,assetReferences,id:s.versions.length+1,status:'planned',prompt,feedback,baseVersion:baseVersion?.id??null,previousImage:baseVersion?.file??null,createdAt:new Date().toISOString(),references:['Style concept','Current functional office','Local Xarts logo'],requirementsVersion:1};s.versions.push(next);s.approvedVersion=null;s.revision++;await save(s);void worker(s,next);return s;
 }catch(e){busy=false;throw e;}}
export async function resumeRoom(){if(busy)return;const s=await roomState();const v=s.versions.at(-1);if(v&&['queued','generating','planned','submitting','paused'].includes(v.status)){busy=true;void worker(s,v);}}
