import {storage} from './storage.mjs';
import {modelInput,queueBase,roomModels,api} from './concept.mjs';
import {dir} from './pipeline.mjs';
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
export function missingItems(assets,jobs=[]){return assets.filter(a=>a.choice!=='reuse'&&a.method!=='Code-built'&&(!a.shared||a.choice==='generate')&&(!a.pilot||a.choice==='generate')&&!jobs.some(j=>j.itemId===a.id));}
export function selectItemBatch(assets,jobs,command){
 if(command.itemIds===undefined)return missingItems(assets,jobs);
 if(!Array.isArray(command.itemIds)||command.itemIds.length<1||command.itemIds.length>6||new Set(command.itemIds).size!==command.itemIds.length)throw Error('Select one to six distinct items');
 return command.itemIds.map(id=>{const asset=assets.find(a=>a.id===id);if(!asset||asset.method==='Code-built')throw Error('Unknown or exact-code item');
 if(jobs.some(j=>j.itemId===id&&['planned','submitting','queued','generating','paused'].includes(j.status)))throw Error('Existing item request must finish first');
 if(jobs.some(j=>j.itemId===id)&&command.regenerate!==true)throw Error('Explicit regeneration required');return asset;});
}
export function itemState(){return storage().get('item-images',{jobs:[]});}
let running=false,starting=false;
function update(id,patch){const s=itemState();Object.assign(s.jobs.find(j=>j.id===id),patch);storage().put('item-images',s);}
export async function startItems(command){if(starting||running)throw Error('An item batch is already running');starting=true;try{const {progress}=await import('./progress.mjs');const p=await progress();if(command.revision!==p.revision||command.roomRevision!==p.room.revision)throw Error('The collection changed. Review the batch again.');if(!p.roomApproved&&!command.delegatedPreview)throw Error('Approve a room design before generating item images');const room=p.room.versions.find(v=>v.id===(command.delegatedPreview?command.roomVersion:p.room.approvedVersion))??p.room.versions.at(-1);if(!room?.file||room.status!=='ready')throw Error('Completed room reference required');const model=command.model??'fal-ai/nano-banana-pro/edit';if(!roomModels.includes(model))throw Error('Unsupported image model');const s=itemState(),missing=selectItemBatch(p.assets,s.jobs,command);if(!missing.length)throw Error('No missing custom images remain');
 const bytes=await readFile(join(dir,room.file));if(createHash('sha256').update(bytes).digest('hex')!==room.sha256)throw Error('Room reference file changed');
 for(const a of missing){s.jobs.push({id:randomUUID(),itemId:a.id,name:a.name,status:'planned',reviewMode:command.delegatedPreview?'Delegated preview work; owner approval pending':'Approved room reference',model,roomVersion:room.id,roomHash:room.sha256,roomFile:room.file,createdAt:new Date().toISOString(),prompt:`Create one isolated, high-quality product concept image of ${a.name}. ${a.description} Image 1 is the selected room concept and style reference; it is not proof of owner approval. Match this object's design, materials, color palette and proportions in that room. Show only this individual item, complete and unobscured against a neutral studio background, with soft grounded shadows and clear geometry for later 3D reconstruction. No collage, labels, invented logos or extra objects. ${['ceo','engineer','qa-person','product-lead'].includes(a.id)?'Exactly one adult, full body, natural proportions, symmetric relaxed A-pose with arms separated from torso, fingers visible, no accessories or tablet, matte woven clothing.':'No people, human figures, mannequins, scale-reference silhouettes, text or numbers anywhere. Blank screens only.'} This is a design concept, not a 3D model. Item feedback: ${a.feedback||'Follow the approved room design.'}`});}storage().put('item-images',s);void resumeItems();return{queued:missing.length};}finally{starting=false;}}
export async function resumeItems(){if(running)return;running=true;try{for(const initial of itemState().jobs){if(!['planned','queued','generating','submitting'].includes(initial.status))continue;const j={...initial};try{if(!j.requestId){if(j.status==='submitting')throw Error('Submission outcome unknown; no automatic paid retry.');const data=await readFile(join(dir,j.roomFile));if(createHash('sha256').update(data).digest('hex')!==j.roomHash)throw Error('Room reference changed');update(j.id,{status:'submitting'});const result=await api('https://queue.fal.run/'+j.model,modelInput(j.model,j.prompt,['data:image/png;base64,'+data.toString('base64')]));j.requestId=result.request_id;if(!j.requestId)throw Error('Provider did not return a request ID');update(j.id,{requestId:j.requestId,status:'queued'});}
 let complete=false;for(let attempt=0;attempt<120;attempt++){const base=queueBase(j.model)+'/requests/'+encodeURIComponent(j.requestId);const status=await api(base+'/status');if(status.status==='COMPLETED'){const result=await api(base);const url=new URL(result.images?.[0]?.url);if(url.protocol!=='https:'||!(url.hostname==='fal.media'||url.hostname.endsWith('.fal.media')))throw Error('Unexpected image host');const response=await fetch(url,{signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error('Image download failed');const chunks=[];let size=0;for await(const chunk of response.body){size+=chunk.length;if(size>25e6)throw Error('Image too large');chunks.push(chunk);}const data=Buffer.concat(chunks);if(data.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('Expected PNG image');const file='item-'+j.id+'.png';await writeFile(join(dir,file),data,{flag:'wx'});update(j.id,{status:'ready',file,sha256:createHash('sha256').update(data).digest('hex'),completedAt:new Date().toISOString()});complete=true;break;}update(j.id,{status:status.status==='IN_QUEUE'?'queued':'generating'});await new Promise(r=>setTimeout(r,5000));}if(!complete)update(j.id,{status:'paused',error:'Polling timed out; no new request submitted.'});}catch(e){update(j.id,{status:'failed',error:e.message});}}}finally{running=false;}}
