import {storage} from './storage.mjs';
import {api} from './concept.mjs';
import {dir,inspectGLB} from './pipeline.mjs';
import {readFile,writeFile,rename} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
export function models(){return storage().get('models',{jobs:[]});}
function patch(id,changes){const s=models();Object.assign(s.jobs.find(j=>j.id===id),changes);storage().put('models',s);}
export async function queueModel(imageId){const images=storage().get('item-images',{jobs:[]});const image=images.jobs.find(j=>j.id===imageId);if(image?.status!=='ready'||image.visualReview?.outcome!=='accepted-for-preview'||image.visualReview.sha256!==image.sha256)throw Error('Visual review of current image required');if(image.itemId==='art')throw Error('Flat artwork uses its image directly');const s=models();if(s.jobs.some(j=>j.imageId===imageId))return;const person=['ceo','engineer','qa-person','product-lead'].includes(image.itemId);s.jobs.push({id:randomUUID(),imageId,itemId:image.itemId,imageFile:image.file,imageHash:image.sha256,status:'planned',person,createdAt:new Date().toISOString(),approval:'Delegated preview, owner approval pending'});storage().put('models',s);}
const active=new Set();
export async function runModels(ids){const queued=models().jobs.filter(j=>(!ids||ids.includes(j.id))&&['planned','submitting','queued','generating'].includes(j.status)&&!active.has(j.id));let cursor=0;await Promise.all([0,1].map(async()=>{while(cursor<queued.length){const j=queued[cursor++];active.add(j.id);try{await work(j);}finally{active.delete(j.id);}}}));}
async function work(j){try{if(!j.requestId){if(j.status==='submitting')throw Error('Unknown submission outcome; no paid retry');const image=await readFile(join(dir,j.imageFile));if(createHash('sha256').update(image).digest('hex')!==j.imageHash)throw Error('Image hash changed');patch(j.id,{status:'submitting'});const result=await api('https://queue.fal.run/fal-ai/meshy/v6-preview/image-to-3d',{image_url:'data:image/png;base64,'+image.toString('base64'),target_polycount:j.person?24000:20000,should_remesh:true,should_texture:true,enable_pbr:true,enable_rigging:j.person,enable_animation:j.person,...(j.person?{pose_mode:'a-pose',animation_action_id:0,rigging_height_meters:1.75}:{}),texture_prompt:'Clean premium materials matching the image. Matte fabric, natural skin, restrained roughness. Do not bake specular highlights into clothing. No emissive materials.'});j.requestId=result.request_id;if(!j.requestId)throw Error('Missing request ID');patch(j.id,{status:'queued',requestId:j.requestId});}
for(let i=0;i<180;i++){const base='https://queue.fal.run/fal-ai/meshy/requests/'+encodeURIComponent(j.requestId);const status=await api(base+'/status');if(status.status==='COMPLETED'){const receipt=await api(base);const asset=receipt.animation_glb??receipt.rigged_character_glb??receipt.model_glb;const url=new URL(asset?.url);if(url.protocol!=='https:'||!(url.hostname==='fal.media'||url.hostname.endsWith('.fal.media')))throw Error('Unexpected asset host');const response=await fetch(url,{signal:AbortSignal.timeout(120000)});if(!response.ok)throw Error('Model download failed');const chunks=[];let total=0;for await(const c of response.body){total+=c.length;if(total>60e6)throw Error('Model exceeds download budget');chunks.push(c);}const bytes=Buffer.concat(chunks),validation=inspectGLB(bytes);if(j.person&&(!validation.skins||!validation.animations))throw Error('Expected rigged animated character');const file='model-'+j.id+'.glb';await writeFile(join(dir,file),bytes,{flag:'wx'});storage().put('model-receipt-'+j.id,receipt);patch(j.id,{status:'ready',file,validation,completedAt:new Date().toISOString()});await publishPreviews();return;}patch(j.id,{status:status.status==='IN_QUEUE'?'queued':'generating'});await new Promise(r=>setTimeout(r,10000));}patch(j.id,{status:'paused',error:'Polling timed out; existing request retained'});}catch(e){patch(j.id,{status:'failed',error:e.message});}}

export async function publishPreviews(){const latest=new Map();for(const j of models().jobs)if(j.status==='ready')latest.set(j.itemId,j);const entries=[...latest.values()].map(j=>({id:j.itemId,file:j.file,sha256:j.validation.sha256,preview:true}));const art=storage().get('item-images',{jobs:[]}).jobs.filter(j=>j.itemId==='art'&&j.status==='ready'&&j.visualReview?.outcome==='accepted-for-preview').at(-1);if(art)entries.push({id:'art',file:art.file,sha256:art.sha256,preview:true});const temporary=join(dir,'office-assets-'+randomUUID()+'.tmp');await writeFile(temporary,JSON.stringify({entries,updatedAt:new Date().toISOString()}));await rename(temporary,join(dir,'office-assets.json'));}
