export {decisionDemos,decisionDemoProject} from '../contracts/decision-definitions.mjs';
export function mountDecisionDemo(root,{onHistory}={}){
 const viewToken={};root.improvementView=viewToken;let last='',selected,items=[],notice='',busy=false;const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 async function refresh(){try{const r=await fetch('/api/improvements',{cache:'no-store'});if(!r.ok)throw Error('No se pudieron leer las propuestas reales.');const data=await r.json();if(data.projectId!=='xarts')throw Error('Proyecto incorrecto');items=data.items;const next=JSON.stringify(items);if(next!==last){last=next;render();}}catch(e){notice=e.message;render();}}
 async function act(d,execute){busy=true;root.improvementsBusy=true;notice=execute?'Enviando la tarea autorizada a Devin…':'Guardando el encargo de planificación…';render();try{
  const session=await fetch('/api/owner-session',{cache:'no-store'});if(!session.ok)throw Error('Sesión de propietario no disponible');const {token}=await session.json();
  const body=execute?{proposalId:d.proposalId,revision:d.revision,taskHash:d.execution.taskHash}:{proposalId:d.proposalId,revision:d.revision,action:'approve_plan',feedback:''};
  const response=await fetch(execute?'/api/improvements/execute':'/api/owner-decisions',{method:'POST',headers:{'Content-Type':'application/json','X-Owner-Token':token},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error??'No se pudo registrar la acción');
  notice=execute?(result.kind==='created'?'Devin ha recibido la tarea. La entrega queda pendiente de QA.':'Consulta el estado registrado de la ejecución.'):'Planificación encargada y guardada. Aún no autoriza ejecución ni entrega.';
 }catch(e){notice=e.message;}finally{busy=false;root.improvementsBusy=false;last='';await refresh();}}
 function render(){root.replaceChildren();root.className='decision-workspace decision-demo';
 const rail=el('aside',undefined,'decision-tray');rail.append(el('span','PROYECTO ANALIZADO · XARTS','decision-kicker'),el('h3','Mejoras para tu librería.','demo-heading'),el('p','Propuestas reales con evidencia y acciones registradas.','decision-empty'));
 const queue=el('nav',undefined,'decision-queue');queue.setAttribute('aria-label','Mejoras de Xarts');
 const d=items.find(d=>d.proposalId===selected)??items[0];selected=d?.proposalId;
 items.forEach((item,i)=>{const b=el('button',undefined,'decision-envelope');b.setAttribute('aria-pressed',String(item.proposalId===selected));const image=el('img');image.src=`/assets/decisions/${item.id}.png`;image.alt='';b.append(image,el('small',`0${i+1} / Xarts`),el('strong',item.title));b.onclick=()=>{selected=item.proposalId;notice='';render();};queue.append(b);});rail.append(queue,el('p','Las acciones se registran de verdad. Las imágenes ilustran la mejora propuesta; no son evidencia de que esté entregada.','decision-consent'));
 if(onHistory){const history=el('button','Historial y pull requests');history.onclick=onHistory;rail.append(history);}
 const sheet=el('article',undefined,'decision-sheet');if(d){sheet.append(el('span','XARTS / MEJORA PROPUESTA','decision-kicker'),el('h3',d.title));const figure=el('figure',undefined,'demo-infographic'),a=el('a');a.href=`/assets/decisions/${d.id}.png`;a.target='_blank';a.rel='noopener';const image=el('img');image.src=a.href;image.alt=`Propuesta: ${d.steps.join(' → ')}`;a.append(image);figure.append(a);const caption=el('figcaption');d.steps.forEach((step,i)=>caption.append(el('span',`0${i+1} ${step}`)));figure.append(caption);sheet.append(figure,el('h4',d.question),el('p',d.why,'decision-intro'));
 const rec=el('section',undefined,'decision-recommendation');rec.append(el('small','RECOMENDACIÓN'),el('p',d.recommendation));sheet.append(rec);
 const detail=el('details',undefined,'decision-evidence');detail.append(el('summary','Evidencia, alternativa y prueba de aceptación'),el('p',d.evidence),el('p',d.validation),el('p',`Alternativa: ${d.alternative}`),el('p',d.boundary),el('small',`Propuesta ${d.proposalId} · revisión ${d.revision.slice(0,12)}`));sheet.append(detail);
 sheet.append(el('p',d.execution.reason,'decision-owner-note'));if(d.execution.scope)sheet.append(el('p','Primera entrega acotada: corregir el signo monetario del waterfall conservando los datos. La precisión configurable queda fuera de esta reparación.','decision-consent'));
 if(d.execution.remoteId)sheet.append(el('p',`Agente: ${d.execution.remoteId} · Uso comunicado: ${d.execution.usageAcu??'pendiente'} ACU`));
 if(d.execution.candidateSha)sheet.append(el('p',`Candidato: ${d.execution.candidateSha.slice(0,12)}. No implica entrega.`));
 const buttons=el('div',undefined,'decision-actions');const plan=el('button',d.resolution?'Decisión de planificación registrada':'Encargar planificación');plan.disabled=busy||!!d.resolution||!!d.execution.remoteId;plan.onclick=()=>act(d,false);buttons.append(plan);
 const run=el('button',d.execution.releaseId?'Primera reparación publicada':d.execution.status==='blocked'?'Entrega bloqueada':d.execution.candidateSha?'Candidato en verificación':d.execution.remoteId?'Reparación enviada a Devin':d.execution.maxAcu?`Ejecutar reparación · máximo ${d.execution.maxAcu} ACU`:'Ejecución pendiente de alcance');run.disabled=busy||!d.execution.canExecute;run.onclick=()=>act(d,true);buttons.append(run);sheet.append(buttons);
 if(d.execution.releaseId){const chat=el('a','Abrir Xarts Chat con la versión activa →');chat.href='http://127.0.0.1:4320/'+(d.execution.replay?.status==='confirmed'?'?run='+encodeURIComponent(d.execution.replay.runId):'');chat.target='_blank';chat.rel='noopener';sheet.append(chat,el('p',`Versión publicada: ${d.execution.releaseId}`));if(d.execution.replay?.status==='confirmed'){const before=el('a','Ver el gráfico original →');before.href='http://127.0.0.1:4320/?run='+encodeURIComponent(d.execution.replay.sourceRunId);before.target='_blank';before.rel='noopener';sheet.append(before,el('p','Replay confirmado. Conserva los avisos de etiquetas abreviadas que no cubre esta reparación.','decision-consent'));}}
 const activity=el('a','Ver actividad real →');activity.href='/activity';sheet.append(activity);
 }else sheet.append(el('p','No hay propuestas de Xarts registradas. No se muestran ejemplos como si fueran trabajo real.'));
 const status=el('p',notice,'decision-notice');status.setAttribute('role','status');sheet.append(status);const reload=el('button','Actualizar estado');reload.disabled=busy;reload.onclick=refresh;sheet.append(reload);root.append(rail,sheet);
 }render();void refresh();const poll=()=>setTimeout(async()=>{if(!root.isConnected||root.improvementView!==viewToken)return;if(!busy)await refresh();poll();},5000);poll();
}
