// Illustrative product directions. Never inserted into the live proposal queue.
export const decisionDemos = [
 {id:'connect',title:'Un proyecto nuevo. Un equipo listo.',question:'¿Abrimos Promote a cualquier repositorio?',why:'Conectar un proyecto debería ser el primer paso, no un proyecto en sí mismo.',recommendation:'Empezar con un adaptador pequeño para Node: errores, feedback y versiones en una sola oficina.',alternative:'Seguir afinando la integración específica de Xarts.',benefit:'Menos configuración para el próximo proyecto.',boundary:'Primero un piloto. Sin prometer compatibilidad universal.',steps:['Conectar','Observar','Priorizar'],scene:'Three distinct small software project buildings connect via turquoise cables to one beautiful central isometric engineering office. A cobalt plug clicks into a port in the foreground. Communicate many projects, one clear control center.'},
 {id:'autonomy',title:'Menos permisos. Más trabajo resuelto.',question:'¿Delegamos el mantenimiento rutinario?',why:'Un fallo conocido no debería esperar a que el fundador revise cada paso.',recommendation:'Delegar correcciones pequeñas dentro de un alcance y presupuesto definidos, con pruebas antes de entregar.',alternative:'Pedir revisión humana para cada reparación.',benefit:'Tu atención vuelve a las decisiones de producto.',boundary:'Cambios de producto, permisos y presupuesto siguen teniendo límites explícitos.',steps:['Detectar','Reparar','Verificar'],scene:'A compact isometric repair workshop. A small broken cobalt software cube enters on the left, an engineer robot with orange arm repairs it in the center, and a pristine turquoise cube exits through a transparent testing gate on the right. A brass boundary rail and small budget gauge communicate controlled autonomy.'},
 {id:'feedback',title:'El feedback encuentra su siguiente paso.',question:'¿Convertimos conversaciones en prioridades?',why:'Los comentarios sirven más cuando se relacionan con problemas reproducibles y necesidades compartidas.',recommendation:'Agrupar señales parecidas y preparar una propuesta con evidencia antes de abrir trabajo nuevo.',alternative:'Revisar comentarios individualmente desde el registro.',benefit:'Un backlog que explica por qué importa cada mejora.',boundary:'La frecuencia de una petición no sustituye el criterio de producto.',steps:['Escuchar','Agrupar','Proponer'],scene:'An isometric editorial sculpture: multiple translucent turquoise speech bubbles and orange message cards flow into three organized trays, then become one beautifully lit cobalt blueprint on a designers desk. A magnifying glass joins the conversation cards to the blueprint. Communicate feedback becoming a focused product direction.'},
 {id:'release',title:'Cada mejora llega con una salida segura.',question:'¿Cerramos el ciclo hasta la entrega?',why:'Una corrección aporta valor cuando llega al proyecto y podemos comprobar su efecto.',recommendation:'Pilotar una entrega gradual: candidato validado, registro de versión y vuelta atrás comprobable.',alternative:'Mantener la publicación como un paso manual.',benefit:'Saber qué versión está activa y cómo recuperarse.',boundary:'Publicar exige pruebas y autorización de despliegue; esta demo no cambia versiones.',steps:['Validar','Publicar','Observar'],scene:'An elegant isometric release pipeline with three architectural gates: testing glass chamber, turquoise delivery platform, and small live project building. A cobalt cube travels along an orange conveyor. A clearly visible curved turquoise return track leads back to a protected previous-version cube. Communicate safe delivery and reversibility.'}
];
export function mountDecisionDemo(root){
 let selected=decisionDemos[0].id;const choices=new Map();
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 function render(){
  root.replaceChildren();root.className='decision-workspace decision-demo';
  const rail=el('aside',undefined,'decision-tray');rail.append(el('span','EL SIGUIENTE CAPÍTULO','decision-kicker'),el('h3','Cuatro caminos.\nTu dirección.','demo-heading'),el('p','Propuestas ilustrativas para el futuro de Promote.','decision-empty'));
  const queue=el('nav',undefined,'decision-queue');queue.setAttribute('aria-label','Propuestas de ejemplo');
  decisionDemos.forEach((d,i)=>{const b=el('button',undefined,'decision-envelope');b.setAttribute('aria-pressed',String(selected===d.id));const thumb=el('img');thumb.src=`/assets/decisions/${d.id}.png`;thumb.alt='';b.append(thumb,el('small',`0${i+1} / ${choices.has(d.id)?'Explorada':'Propuesta'}`),el('strong',d.title));b.onclick=()=>{selected=d.id;render();};queue.append(b);});rail.append(queue,el('p','DEMO · Las elecciones se guardan solo mientras esta vista permanece abierta. No lanzan agentes ni publican cambios.','decision-consent'));
  const d=decisionDemos.find(d=>d.id===selected),sheet=el('article',undefined,'decision-sheet');
  sheet.append(el('span','PROMOTE / DIRECCIONES DE PRODUCTO','decision-kicker'),el('h3',d.title));
  const figure=el('figure',undefined,'demo-infographic'),link=el('a');link.href=`/assets/decisions/${d.id}.png`;link.target='_blank';link.rel='noopener';link.setAttribute('aria-label','Ampliar infografía');const image=el('img');image.src=link.href;image.alt=`${d.title} Infografía isométrica: ${d.steps.join(' → ')}.`;image.width=1536;image.height=1024;link.append(image);figure.append(link);const caption=el('figcaption');d.steps.forEach((s,i)=>caption.append(el('span',`0${i+1}  ${s}`)));figure.append(caption);sheet.append(figure,el('h4',d.question),el('p',d.why,'decision-intro'));
  const recommendation=el('section',undefined,'decision-recommendation');recommendation.append(el('small','RECOMENDACIÓN DEL EQUIPO'),el('p',d.recommendation));sheet.append(recommendation);
  const detail=el('details',undefined,'decision-evidence');detail.append(el('summary','Qué ganamos y qué límites mantenemos'),el('p',d.benefit),el('p',d.boundary),el('p',`Alternativa: ${d.alternative}`));sheet.append(detail);
  const buttons=el('div',undefined,'decision-actions');for(const label of ['Explorar esta dirección','Mantener el foco actual']){const b=el('button',label);b.onclick=()=>{choices.set(d.id,label);render();};buttons.append(b);}sheet.append(buttons);const status=el('p',choices.has(d.id)?`Elección de ejemplo: ${choices.get(d.id)}. No se ha enviado ninguna aprobación real.`:'Elige una dirección para probar la experiencia.','decision-notice');status.setAttribute('role','status');sheet.append(status);root.append(rail,sheet);
 }render();
}
